Add timeout feature
chawlapalak/Url-Inspector pull request #7
Opened 2020-10-01 02:44 UTC by Shinh18

#### Fixed #6 

- Added Timeout of 1.5 secs to axios (Optimization)

- Updated README.md to include this feature and elaborated on the existing features

- Improved styling and indentation

2020-10-02 22:33 UTC, chawlapalak commented
Hi Muskan:

I am unable to see your branch in my repository. Also, there is a merge conflict in the Readme file. So please resolve this merge conflict and add the changes in the branch visible to me.

Thanks,
Palak

2020-10-02 22:40 UTC, Shinh18 commented
Hey Palak, 
You cannot see the branch in your repo because I forked your repo, cloned the one I forked, made a branch in that repo and then made changes and pushed. 
So I created this pull request from the branch in my forked repo to your master branch. This is what I think we have to do. 
Also, the readme file conflict will be resolved once you review the file and accept the changes, I think. 

I made the mistake of branch name but I don't think I can change that now.

2020-10-02 22:55 UTC, Shinh18 commented
Hey Palak, 
I resolved the conflict in the readme file. There are no more conflicts.

Thanks,
Muskan

2020-10-03 00:00 UTC, chawlapalak requested changes
Hi, 
Please correct the spellings in the readme file. Thanks.

Best,
Palak

2020-10-03 00:00 UTC, chawlapalak commented on README.md
> +# Instalation
Spelling mistake, please correct.

2020-10-03 00:00 UTC, chawlapalak commented on README.md
> +    url-inspector -v or -V or --versin
Version spelled wrong. Please fix.

2020-10-03 00:12 UTC, Shinh18 commented on README.md
> +# Instalation
Fixed.

2020-10-03 00:12 UTC, Shinh18 commented on README.md
> +    url-inspector -v or -V or --versin
Fixed.

2020-10-03 00:13 UTC, chawlapalak approved these changes

2020-10-03 00:14 UTC, merged

2020-10-03 00:14 UTC, chawlapalak commented
Hi,
Approved.
Thanks,
Palak Chawla